---
- hosts: localhost
  vars:
    bench_repo_path: "/home/{{ ansible_user_id }}/.bench"
    bench_path: "/home/{{ ansible_user_id }}/frappe-bench"
    mysql_config_template: "templates/simple_mariadb_config.cnf"
    mysql_conf_dir: /etc/my.cnf.d/
    wkhtmltopdf_version: 0.12.2.1

  tasks:

  - name: development tools package
    yum: name="@Development tools" state=present
    become: yes
    become_user: root

  - name: install prequisites
    yum: pkg={{ item }} state=present
    with_items:
      # basic installs
      - redis

      # for mariadb
      - libselinux-python
      - mysql-devel
      - mysql-libs

      # for wkhtmltopdf
      - libXrender
      - libXext
      - xorg-x11-fonts-75dpi
      - xorg-x11-fonts-Type1

      # for Pillow
      - libjpeg-devel
      - zlib-devel
      - libzip-devel
      - freetype-devel
      - lcms2-devel
      - libwebp-devel
      - libtiff-devel
      - tcl-devel
      - tk-devel
    become: yes
    become_user: root

  - name: Get nodejs 6.x bash script
    get_url:
      url: 'https://rpm.nodesource.com/setup_6.x'
      dest: '/tmp/setup_6.x'
      mode: 0644
    become: yes
    become_user: root

  - name: Run nodejs 6.x bash script
    command: /bin/bash /tmp/setup_6.x
    become: yes
    become_user: root

  - name: Install nodejs
    yum:
      name: nodejs
      state: present
    become: yes
    become_user: root

  # install MariaDB
  - include: includes/mariadb_centos.yml

  # install WKHTMLtoPDF
  - include: includes/wkhtmltopdf_centos.yml

  # setup MariaDB
  - include: includes/setup_mariadb.yml

  # setup frappe-bench
  - include: includes/setup_bench.yml
    when: not run_travis and not without_bench_setup

  # setup development environment
  - include: includes/setup_dev_env.yml
    when: not run_travis and not production
