---
  - hosts: localhost

  # Install the common pre-requisites for the setting up bench
  - include: ../develop/install.yml

  # Install the production environment
  - include: includes/setup_prod_env.yml

  # Setup Bench for production environment
  - include: includes/setup_bench_production.yml
    when: not run_travis

  # Setup SELinux Policy, Optional can be done later
  # - include: includes/setup_selinux_policy.yml